### ISSUE TITLE
Автозапуск по расписанию

### ISSUE THREAD

**Issue by Wh1te-T** [Nikovit/bot_rss_to_telegram#1]
Привет, как запустить бота по расписанию?

**Comment by Nikovit** [comment]
Настроить запуск скрипта по расписанию в линуксе можно через cron
команда crontab -e, в этом примере бот запускается каждый час:

`0 */1 * * * python3 /root/script/bot/main.py`

В windows в Планировщике заданий настраиваем запуск скрипта с нужным интервалом.
